[versions]
assertj = "3.27.7"
hivemq-mqttClient = "1.4.0"
hivemq-platform = "4.54.0"
jetbrains-annotations = "26.1.0"
junit-jupiter = "5.11.3"
mockserver = "7.6.0"
shrinkwrap = "1.2.6"
testcontainers = "1.21.4"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
hivemq-enterpriseSecurityExtension-customizationSdk = { module = "com.hivemq:hivemq-enterprise-security-extension-customization-sdk", version.ref = "hivemq-platform" }
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
mockserver-client = { module = "org.mock-server:mockserver-client-java-no-dependencies", version.ref = "mockserver" }
shrinkwrap-api = { module = "org.jboss.shrinkwrap:shrinkwrap-api", version.ref = "shrinkwrap" }
shrinkwrap-impl = { module = "org.jboss.shrinkwrap:shrinkwrap-impl-base", version.ref = "shrinkwrap" }
testcontainers-hivemq = { module = "org.testcontainers:hivemq", version.ref = "testcontainers" }
testcontainers-mockserver = { module = "org.testcontainers:mockserver", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }

[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.3.0" }
spotless = { id = "com.diffplug.spotless", version = "8.10.2" }
